name = "dc-55r"  # 必须与你在 Cloudflare 仪表板中的 Worker 名称完全一致
main = "app.js" # 你的 Worker 代码文件名，请根据实际情况修改
compatibility_date = "2026-09-11" # 使用一个近期的日期即可

# 如果你已经绑定了 D1 数据库，在这里添加配置，这样通过 Git 部署时绑定才不会丢失
[[d1_databases]]
binding = "DB" # 与代码中 env.DB 的变量名一致
database_name = "word-db"
database_id = "063886ea-f81d-4d81-b109-c63ce0368812" # 在 D1 数据库详情页可以找到
